FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copiar arquivos de projeto de todas as pastas
COPY *.sln .
COPY ComparadorPrecos.API/*.csproj ./ComparadorPrecos.API/
COPY ComparadorPrecos.Application/*.csproj ./ComparadorPrecos.Application/
COPY ComparadorPrecos.Core/*.csproj ./ComparadorPrecos.Core/
COPY ComparadorPrecos.Infrastructure/*.csproj ./ComparadorPrecos.Infrastructure/

# Restaurar dependências
RUN dotnet restore

# Copiar todo o código
COPY . .

# Build e publish do projeto API
WORKDIR /src/ComparadorPrecos.API
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 80
ENTRYPOINT ["dotnet", "ComparadorPrecos.API.dll"]