FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["ComparadorPrecos.API.csproj", "."]
RUN dotnet restore "ComparadorPrecos.API.csproj"
COPY . .
RUN dotnet build "ComparadorPrecos.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ComparadorPrecos.API.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 80
ENTRYPOINT ["dotnet", "ComparadorPrecos.API.dll"]